services:
  nginx:
    container_name: bsk_nginx
    image: nginx:latest
    env_file:
      - ./.env
    ports:
      - ${BSK_NGINX_PORT_EXTERNAL}:${BSK_NGINX_PORT_INTERNAL}

    environment:
      BSK_NGINX_HOST: ${BSK_NGINX_HOST}
      BSK_NGINX_PORT: ${BSK_NGINX_PORT_INTERNAL}
      BSK_NGINX_API_URL: ${BSK_NGINX_API_URL}
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./bsk_frontend/dist:/var/www/website
    networks:
      - bsk_shared_network

  model:
    container_name: bsk_model
    image: cinkus/phishing-detector-api
    networks:
      - bsk_shared_network

networks:
  bsk_shared_network: